[package]
name = "ironfish-frost"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

authors = ["Iron Fish <contact@ironfish.network> (https://ironfish.network)"]
homepage = "https://ironfish.network/"
repository = "https://github.com/iron-fish/ironfish-frost"

[dependencies]
ed25519-dalek = { version = "2.1.0", features = ["rand_core"] }
rand_core = "0.6.4"
reddsa = { git = "https://github.com/ZcashFoundation/reddsa.git", features = ["frost", "frost-rerandomized"] }
x25519-dalek = { version = "2.0.0", features = ["static_secrets"] }

[dev-dependencies]
rand = "0.8.5"
